
[general]
	#The material blacklist of this module.
	materialBlacklist = ["brick", "nether_brick", "obsidian", "prismarine", "salt", "dragonstone", "mana_diamond", "certus", "certus_quartz", "charged_certus_quartz"]

