
[general]
	#The material blacklist of this module.
	materialBlacklist = ["amber", "brass", "brick", "invar", "lapis_lazuli", "nether_brick", "obsidian", "platinum", "prismarine", "salt", "titanium", "tungsten", "zinc"]

