"Allow all items to be added" = false
"Whitelisted Items" = ["Whitelisted Items", "tetra:holo", "cookingforblockheads:recipe_book", "cookingforblockheads:no_filter_edition"]
"Whitelisted Names" = ["book", "tome", "lexicon", "nomicon", "manual", "knowledge", "pedia", "compendium", "guide", "codex", "journal"]
"Blacklisted Mods" = []
"Mod Aliases" = ["nautralpledge=botania", "mythicbotany=botania", "thermalexpansion=thermalfoundation", "thermaldynamics=thermalfoundation", "thermalcultivation=thermalfoundation", "redstonearsenal=thermalfoundation", "rftoolsdim=rftools", "rftoolspower=rftools", "rftoolscontrol=rftools", "animus=bloodmagic", "integrateddynamics=integratedtunnels", "mekanismgenerators=mekanism", "mekanismtools=mekanism", "deepresonance=rftools", "xnet=rftools"]

