
#World Gen - Ore Generation Configuration
["Ore Config: coal"]
	#Average ores per Chunk [Range: 0-64, Default: 20]
	#Range: 0 ~ 64
	count = 20
	#Activate/Deactivate the World Gen [Default: true]
	active = true
	#Configure the ore Vein Size [Default: 17]
	#Range: 0 ~ 64
	vein_size = 17
	#Baseline Y-Level [Range: 0-256, Default: 60]
	#Range: 0 ~ 256
	baseline = 60
	#Spread Amount (# of Y-Levels above and below the baseline) [Range: 0-256, Default: 60]
	#Range: 0 ~ 256
	spread = 60

["Ore Config: iron"]
	#Average ores per Chunk [Range: 0-64, Default: 20]
	#Range: 0 ~ 64
	count = 20
	#Activate/Deactivate the World Gen [Default: true]
	active = true
	#Configure the ore Vein Size [Default: 11]
	#Range: 0 ~ 64
	vein_size = 11
	#Baseline Y-Level [Range: 0-256, Default: 32]
	#Range: 0 ~ 256
	baseline = 32
	#Spread Amount (# of Y-Levels above and below the baseline) [Range: 0-256, Default: 32]
	#Range: 0 ~ 256
	spread = 32

["Ore Config: gold"]
	#Average ores per Chunk [Range: 0-64, Default: 7]
	#Range: 0 ~ 64
	count = 7
	#Activate/Deactivate the World Gen [Default: true]
	active = true
	#Configure the ore Vein Size [Default: 8]
	#Range: 0 ~ 64
	vein_size = 8
	#Baseline Y-Level [Range: 0-256, Default: 16]
	#Range: 0 ~ 256
	baseline = 16
	#Spread Amount (# of Y-Levels above and below the baseline) [Range: 0-256, Default: 16]
	#Range: 0 ~ 256
	spread = 16

["Ore Config: diamond"]
	#Average ores per Chunk [Range: 0-64, Default: 3]
	#Range: 0 ~ 64
	count = 3
	#Activate/Deactivate the World Gen [Default: true]
	active = true
	#Configure the ore Vein Size [Default: 8]
	#Range: 0 ~ 64
	vein_size = 8
	#Baseline Y-Level [Range: 0-256, Default: 8]
	#Range: 0 ~ 256
	baseline = 8
	#Spread Amount (# of Y-Levels above and below the baseline) [Range: 0-256, Default: 8]
	#Range: 0 ~ 256
	spread = 8

["Ore Config: emerald"]
	#Average ores per Chunk [Range: 0-64, Default: 1]
	#Range: 0 ~ 64
	count = 1
	#Activate/Deactivate the World Gen [Default: true]
	active = true
	#Configure the ore Vein Size [Default: 6]
	#Range: 0 ~ 64
	vein_size = 6
	#Baseline Y-Level [Range: 0-256, Default: 96]
	#Range: 0 ~ 256
	baseline = 96
	#Spread Amount (# of Y-Levels above and below the baseline) [Range: 0-256, Default: 32]
	#Range: 0 ~ 256
	spread = 32

["Ore Config: lapis"]
	#Average ores per Chunk [Range: 0-64, Default: 4]
	#Range: 0 ~ 64
	count = 4
	#Activate/Deactivate the World Gen [Default: true]
	active = true
	#Configure the ore Vein Size [Default: 7]
	#Range: 0 ~ 64
	vein_size = 7
	#Baseline Y-Level [Range: 0-256, Default: 8]
	#Range: 0 ~ 256
	baseline = 8
	#Spread Amount (# of Y-Levels above and below the baseline) [Range: 0-256, Default: 8]
	#Range: 0 ~ 256
	spread = 8

["Ore Config: redstone"]
	#Average ores per Chunk [Range: 0-64, Default: 9]
	#Range: 0 ~ 64
	count = 9
	#Activate/Deactivate the World Gen [Default: true]
	active = true
	#Configure the ore Vein Size [Default: 14]
	#Range: 0 ~ 64
	vein_size = 14
	#Baseline Y-Level [Range: 0-256, Default: 8]
	#Range: 0 ~ 256
	baseline = 8
	#Spread Amount (# of Y-Levels above and below the baseline) [Range: 0-256, Default: 8]
	#Range: 0 ~ 256
	spread = 8

["Ore Config: copper"]
	#Average ores per Chunk [Range: 0-64, Default: 20]
	#Range: 0 ~ 64
	count = 20
	#Activate/Deactivate the World Gen [Default: true]
	active = true
	#Configure the ore Vein Size [Default: 7]
	#Range: 0 ~ 64
	vein_size = 7
	#Baseline Y-Level [Range: 0-256, Default: 52]
	#Range: 0 ~ 256
	baseline = 52
	#Spread Amount (# of Y-Levels above and below the baseline) [Range: 0-256, Default: 8]
	#Range: 0 ~ 256
	spread = 8

["Ore Config: aluminum"]
	#Average ores per Chunk [Range: 0-64, Default: 8]
	#Range: 0 ~ 64
	count = 8
	#Activate/Deactivate the World Gen [Default: true]
	active = true
	#Configure the ore Vein Size [Default: 5]
	#Range: 0 ~ 64
	vein_size = 5
	#Baseline Y-Level [Range: 0-256, Default: 60]
	#Range: 0 ~ 256
	baseline = 60
	#Spread Amount (# of Y-Levels above and below the baseline) [Range: 0-256, Default: 10]
	#Range: 0 ~ 256
	spread = 10

["Ore Config: silver"]
	#Average ores per Chunk [Range: 0-64, Default: 8]
	#Range: 0 ~ 64
	count = 8
	#Activate/Deactivate the World Gen [Default: true]
	active = true
	#Configure the ore Vein Size [Default: 5]
	#Range: 0 ~ 64
	vein_size = 5
	#Baseline Y-Level [Range: 0-256, Default: 34]
	#Range: 0 ~ 256
	baseline = 34
	#Spread Amount (# of Y-Levels above and below the baseline) [Range: 0-256, Default: 4]
	#Range: 0 ~ 256
	spread = 4

["Ore Config: lead"]
	#Average ores per Chunk [Range: 0-64, Default: 8]
	#Range: 0 ~ 64
	count = 8
	#Activate/Deactivate the World Gen [Default: true]
	active = true
	#Configure the ore Vein Size [Default: 5]
	#Range: 0 ~ 64
	vein_size = 5
	#Baseline Y-Level [Range: 0-256, Default: 36]
	#Range: 0 ~ 256
	baseline = 36
	#Spread Amount (# of Y-Levels above and below the baseline) [Range: 0-256, Default: 4]
	#Range: 0 ~ 256
	spread = 4

["Ore Config: nickel"]
	#Average ores per Chunk [Range: 0-64, Default: 8]
	#Range: 0 ~ 64
	count = 8
	#Activate/Deactivate the World Gen [Default: true]
	active = true
	#Configure the ore Vein Size [Default: 4]
	#Range: 0 ~ 64
	vein_size = 4
	#Baseline Y-Level [Range: 0-256, Default: 32]
	#Range: 0 ~ 256
	baseline = 32
	#Spread Amount (# of Y-Levels above and below the baseline) [Range: 0-256, Default: 8]
	#Range: 0 ~ 256
	spread = 8

["Ore Config: uranium"]
	#Average ores per Chunk [Range: 0-64, Default: 6]
	#Range: 0 ~ 64
	count = 6
	#Activate/Deactivate the World Gen [Default: true]
	active = true
	#Configure the ore Vein Size [Default: 6]
	#Range: 0 ~ 64
	vein_size = 6
	#Baseline Y-Level [Range: 0-256, Default: 12]
	#Range: 0 ~ 256
	baseline = 12
	#Spread Amount (# of Y-Levels above and below the baseline) [Range: 0-256, Default: 8]
	#Range: 0 ~ 256
	spread = 8

["Ore Config: osmium"]
	#Average ores per Chunk [Range: 0-64, Default: 17]
	#Range: 0 ~ 64
	count = 17
	#Activate/Deactivate the World Gen [Default: true]
	active = true
	#Configure the ore Vein Size [Default: 6]
	#Range: 0 ~ 64
	vein_size = 6
	#Baseline Y-Level [Range: 0-256, Default: 32]
	#Range: 0 ~ 256
	baseline = 32
	#Spread Amount (# of Y-Levels above and below the baseline) [Range: 0-256, Default: 12]
	#Range: 0 ~ 256
	spread = 12

["Ore Config: tin"]
	#Average ores per Chunk [Range: 0-64, Default: 20]
	#Range: 0 ~ 64
	count = 20
	#Activate/Deactivate the World Gen [Default: true]
	active = true
	#Configure the ore Vein Size [Default: 7]
	#Range: 0 ~ 64
	vein_size = 7
	#Baseline Y-Level [Range: 0-256, Default: 47]
	#Range: 0 ~ 256
	baseline = 47
	#Spread Amount (# of Y-Levels above and below the baseline) [Range: 0-256, Default: 7]
	#Range: 0 ~ 256
	spread = 7

["Ore Config: zinc"]
	#Average ores per Chunk [Range: 0-64, Default: 9]
	#Range: 0 ~ 64
	count = 9
	#Activate/Deactivate the World Gen [Default: true]
	active = true
	#Configure the ore Vein Size [Default: 5]
	#Range: 0 ~ 64
	vein_size = 5
	#Baseline Y-Level [Range: 0-256, Default: 42]
	#Range: 0 ~ 256
	baseline = 42
	#Spread Amount (# of Y-Levels above and below the baseline) [Range: 0-256, Default: 8]
	#Range: 0 ~ 256
	spread = 8

["Ore Config: certus_quartz"]
	#Average ores per Chunk [Range: 0-64, Default: 16]
	#Range: 0 ~ 64
	count = 16
	#Activate/Deactivate the World Gen [Default: true]
	active = false
	#Configure the ore Vein Size [Default: 8]
	#Range: 0 ~ 64
	vein_size = 8
	#Baseline Y-Level [Range: 0-256, Default: 32]
	#Range: 0 ~ 256
	baseline = 32
	#Spread Amount (# of Y-Levels above and below the baseline) [Range: 0-256, Default: 32]
	#Range: 0 ~ 256
	spread = 32

["Ore Config: charged_certus_quartz"]
	#Average ores per Chunk [Range: 0-64, Default: 8]
	#Range: 0 ~ 64
	count = 8
	#Activate/Deactivate the World Gen [Default: true]
	active = false
	#Configure the ore Vein Size [Default: 4]
	#Range: 0 ~ 64
	vein_size = 4
	#Baseline Y-Level [Range: 0-256, Default: 16]
	#Range: 0 ~ 256
	baseline = 16
	#Spread Amount (# of Y-Levels above and below the baseline) [Range: 0-256, Default: 16]
	#Range: 0 ~ 256
	spread = 16

["Ore Config: fluorite"]
	#Average ores per Chunk [Range: 0-64, Default: 6]
	#Range: 0 ~ 64
	count = 6
	#Activate/Deactivate the World Gen [Default: true]
	active = true
	#Configure the ore Vein Size [Default: 12]
	#Range: 0 ~ 64
	vein_size = 12
	#Baseline Y-Level [Range: 0-256, Default: 16]
	#Range: 0 ~ 256
	baseline = 16
	#Spread Amount (# of Y-Levels above and below the baseline) [Range: 0-256, Default: 16]
	#Range: 0 ~ 256
	spread = 16

["Ore Config: bitumen"]
	#Average ores per Chunk [Range: 0-64, Default: 2]
	#Range: 0 ~ 64
	count = 2
	#Activate/Deactivate the World Gen [Default: true]
	active = true
	#Configure the ore Vein Size [Default: 18]
	#Range: 0 ~ 64
	vein_size = 18
	#Baseline Y-Level [Range: 0-256, Default: 100]
	#Range: 0 ~ 256
	baseline = 100
	#Spread Amount (# of Y-Levels above and below the baseline) [Range: 0-256, Default: 60]
	#Range: 0 ~ 256
	spread = 60

#World Gen - Ore Generation on Strata Stone Type
["Stratum Config: minecraft_stone"]
	active = true

["Stratum Config: minecraft_andesite"]
	active = true

["Stratum Config: create_gabbro"]
	active = true

["Stratum Config: create_limestone"]
	active = true

["Stratum Config: create_scoria"]
	active = true

["Stratum Config: create_weathered_limestone"]
	active = true

["Stratum Config: quark_jasper"]
	active = true

["Stratum Config: quark_marble"]
	active = true

["Stratum Config: quark_slate"]
	active = true

["Ore Config: cinnabar"]
	#Average ores per Chunk [Range: 0-64, Default: 4]
	#Range: 0 ~ 64
	count = 4
	#Activate/Deactivate the World Gen [Default: true]
	active = true
	#Configure the ore Vein Size [Default: 5]
	#Range: 0 ~ 64
	vein_size = 5
	#Baseline Y-Level [Range: 0-256, Default: 10]
	#Range: 0 ~ 256
	baseline = 10
	#Spread Amount (# of Y-Levels above and below the baseline) [Range: 0-256, Default: 6]
	#Range: 0 ~ 256
	spread = 6

["Ore Config: apatite"]
	#Average ores per Chunk [Range: 0-64, Default: 2]
	#Range: 0 ~ 64
	count = 2
	#Activate/Deactivate the World Gen [Default: true]
	active = true
	#Configure the ore Vein Size [Default: 22]
	#Range: 0 ~ 64
	vein_size = 22
	#Baseline Y-Level [Range: 0-256, Default: 96]
	#Range: 0 ~ 256
	baseline = 96
	#Spread Amount (# of Y-Levels above and below the baseline) [Range: 0-256, Default: 32]
	#Range: 0 ~ 256
	spread = 32

["Ore Config: sulfur"]
	#Average ores per Chunk [Range: 0-64, Default: 3]
	#Range: 0 ~ 64
	count = 3
	#Activate/Deactivate the World Gen [Default: true]
	active = true
	#Configure the ore Vein Size [Default: 7]
	#Range: 0 ~ 64
	vein_size = 7
	#Baseline Y-Level [Range: 0-256, Default: 8]
	#Range: 0 ~ 256
	baseline = 8
	#Spread Amount (# of Y-Levels above and below the baseline) [Range: 0-256, Default: 8]
	#Range: 0 ~ 256
	spread = 8

["Ore Config: potassium_nitrate"]
	#Average ores per Chunk [Range: 0-64, Default: 4]
	#Range: 0 ~ 64
	count = 4
	#Activate/Deactivate the World Gen [Default: true]
	active = true
	#Configure the ore Vein Size [Default: 5]
	#Range: 0 ~ 64
	vein_size = 5
	#Baseline Y-Level [Range: 0-256, Default: 25]
	#Range: 0 ~ 256
	baseline = 25
	#Spread Amount (# of Y-Levels above and below the baseline) [Range: 0-256, Default: 7]
	#Range: 0 ~ 256
	spread = 7

["Ore Config: arcane"]
	#Average ores per Chunk [Range: 0-64, Default: 5]
	#Range: 0 ~ 64
	count = 5
	#Activate/Deactivate the World Gen [Default: true]
	active = true
	#Configure the ore Vein Size [Default: 6]
	#Range: 0 ~ 64
	vein_size = 6
	#Baseline Y-Level [Range: 0-256, Default: 33]
	#Range: 0 ~ 256
	baseline = 33
	#Spread Amount (# of Y-Levels above and below the baseline) [Range: 0-256, Default: 13]
	#Range: 0 ~ 256
	spread = 13

