
#Mod integration config
[Integration]
	#Enables Ender Storage integration. Default value is true
	EnderStorage = true
	#Enables Immersive Engineering integration. Default value is true
	ImmersiveEngineering = true
	#Enables Iron Chest integration. Default value is true
	IronChest = true
	#Enables Pneumaticcraft integration. Default value is true
	Pneumaticcraft = true
	#Enables Expanded Storage integration. Default value is true
	ExpandedStroage = true

	#Industrial Foregoing
	[Integration.IndustrialForegoing]
		#Enables Black Hole Unit integration. Default value is true
		BlackHoleUnit = true
		#Enables Black Hole Controller integration. Default value is true
		BlackHoleController = true

	#Storage Drawers
	[Integration.StorageDrawers]
		#Enables standard drawers integration. Default value is true
		Standard = true
		#Enables compacting drawers integration. Default value is true
		Compacting = true

