
#Storage Settings
[storage]
	#The amount of slots the storage stabilizer tier 1 provides.
	stabilizerTier1Slots = 128
	#The amount of slots the storage stabilizer tier 2 provides.
	stabilizerTier2Slots = 256
	#The amount of slots the storage stabilizer tier 3 provides.
	stabilizerTier3Slots = 512
	#The amount of slots the storage stabilizer tier 4 provides.
	stabilizerTier4Slots = 1024
	#The amount of slots the storage actuator provides.
	controllerBaseSlots = 128

#WorldGen Settings
[worldgen]

	#Underground Grove Settings
	[worldgen.underground_grove]
		#The chance grass will spawn in the underground grove.
		grassChance = 0.6
		#The chance small trees will spawn in the underground grove.
		treeChance = 0.1
		#The chance vines will spawn in the underground grove.
		vineChance = 0.3
		#The chance glowstone will spawn in the ceiling of the underground grove.
		ceilingLightChance = 0.1

#Ritual Settings
[rituals]
	#Enables the ritual to clear rainy weather.
	enableClearWeatherRitual = true
	#Enables the ritual to start rainy weather.
	enableRainWeatherRitual = true
	#Enables the ritual to start a thunderstorm.
	enableThunderWeatherRitual = true
	#Enables the ritual to set time to day.
	enableDayTimeRitual = true
	#Enables the ritual to set time to night.
	enableNightTimeRitual = true

#Dimensional Mineshaft Settings
[dimensional_mineshaft]

	#Miner Spirit Settings
	[dimensional_mineshaft.miner_foliot_unspecialized]
		#The amount of time it takes the spirit to perform one mining operation.
		maxMiningTime = 400
		#The amount of blocks the spirit will obtain per mining operation
		rollsPerOperation = 1
		#The amount of mining operations the spirit can perform before breaking.
		durability = 1000

	#Miner Spirit Settings
	[dimensional_mineshaft.miner_djinni_ores]
		#The amount of time it takes the spirit to perform one mining operation.
		maxMiningTime = 400
		#The amount of blocks the spirit will obtain per mining operation
		rollsPerOperation = 1
		#The amount of mining operations the spirit can perform before breaking.
		durability = 100

