rocks = true
twigs = true
fallenLeaves = true
bones = true
charredBones = true
iceChunks = true
pinecones = true
seashells = true
seaOats = true
cattails = true
barkMushrooms = true
cobwebs = true
bushes = true
glowcap = true
#Seagrass in lakes
moreSeagrass = true
#Denser river grass
moreGrassInRivers = true
#Tropical fish in jungles
jungleTropicalFish = true

