
#Here are configs that are only needed very early when the mod starts to disable blocks & tabs
[registration]

	[registration.blocks]
		planter = true
		clock_block = true
		pedestal = false
		wind_vane = true
		redstone_illuminator = false
		notice_board = true
		crank = false
		jar = true
		faucet = true
		turn_table = false
		piston_launcher = true
		speaker_block = true
		sign_post = true
		hanging_sign = true
		bellows = true
		sconce = true
		sconce_green = true
		sconce_ender = true
		sconce_soul = true
		candelabra = true
		cage = false
		item_shelf = true
		sconce_lever = true
		cog_block = false
		candle_holder = true
		globe = true
		hourglass = true
		sack = false
		blackboard = false
		safe = true
		copper_lantern = true
		flute = true
		gold_trapdoor = true
		gold_door = true
		bamboo_spikes = true
		stone_lamp = false
		checker_block = true
		netherite_door = true
		netherite_trapdoor = true
		pancake = true
		lock_block = true
		flax = true
		rope = true
		rope_arrow = true
		pulley_block = true
		fodder = true
		bomb = true
		#WIP
		laser_block = false
		flag = true
		magma_cream_block = false
		crimson_lantern = true
		goblet = true
		raked_gravel = true
		i_want_flags = false

	[registration.entities]
		firefly = true

	[registration.general]
		#Enable Creative Tab
		creative_tab = false
		#Set to false to disable custom dispenser behaviors (i.e: filling jars) if for some reason they are causing trouble
		dispensers = true
		#Creates a creative tab full of filled jars
		jar_tab = false

